[package]
name = "game-of-life"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston = "0.55.0"
piston2d-opengl_graphics = "0.84.0"
piston_window = "0.131.0"
pistoncore-glutin_window = "0.72.0"
